<?php
require_once __DIR__.'/../config/config.php'; $pdo=db(); $cid=current_company_id();
ensure_transaction_documentation_columns();
$customers=$pdo->prepare("SELECT id,customer_no,name FROM customers WHERE company_id=? AND status='active' ORDER BY name");$customers->execute([$cid]);$customers=$customers->fetchAll();
$wastes=$pdo->prepare("SELECT * FROM waste_types WHERE company_id=? AND status=1 ORDER BY name");$wastes->execute([$cid]);$wastes=$wastes->fetchAll();
$recent=$pdo->prepare("SELECT d.deposit_date,d.receipt_no,c.name customer,d.total_weight,d.total_amount,d.status FROM deposits d LEFT JOIN customers c ON c.id=d.customer_id WHERE d.company_id=? ORDER BY d.id DESC LIMIT 10");$recent->execute([$cid]);$recentDeposits=$recent->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$pdo->beginTransaction();try{
$receipt='SET-'.date('YmdHis').'-'.random_int(100,999);$weights=$_POST['weight']??[];$ids=$_POST['waste_type_id']??[];$totalW=0;$total=0;$details=[];
foreach($ids as $i=>$wid){$wt=(float)($weights[$i]??0);if($wt<=0)continue;$s=$pdo->prepare("SELECT buy_price FROM waste_types WHERE id=? AND company_id=?");$s->execute([$wid,$cid]);$price=(float)$s->fetchColumn();$sub=$wt*$price;$totalW+=$wt;$total+=$sub;$details[]=[$wid,$wt,$price,$sub];}
if(!$details)throw new Exception('Minimal satu jenis sampah harus diisi.');
$documentation=store_transaction_documentation('documentation','deposit');
$s=$pdo->prepare("INSERT INTO deposits(company_id,customer_id,receipt_no,deposit_date,total_weight,total_amount,notes,documentation) VALUES(?,?,?,?,?,?,?,?)");$s->execute([$cid,$_POST['customer_id'],$receipt,$_POST['deposit_date'],$totalW,$total,$_POST['notes'],$documentation]);$did=$pdo->lastInsertId();
foreach($details as $d){$pdo->prepare("INSERT INTO deposit_details(deposit_id,waste_type_id,weight_kg,price_per_kg,subtotal) VALUES(?,?,?,?,?)")->execute([$did,...$d]);$pdo->prepare("UPDATE waste_types SET stock_kg=stock_kg+? WHERE id=? AND company_id=?")->execute([$d[1],$d[0],$cid]);}
$pdo->prepare("UPDATE customers SET balance=balance+? WHERE id=? AND company_id=?")->execute([$total,$_POST['customer_id'],$cid]);$pdo->commit();flash('success',"Setoran tersimpan. No: $receipt, nilai: ".rupiah($total));redirect('deposit.php');
}catch(Throwable $e){$pdo->rollBack();flash('error',$e->getMessage());redirect('deposit.php');}}
$active='deposit';$title='Setoran Sampah';require __DIR__.'/../includes/header.php';?>
<div class="section-head">
  <div><h1>Terima Setoran Sampah</h1><p class="muted">Catat setoran sampah dari nasabah dan tambahkan otomatis ke saldo.</p></div>
  <div style="display:flex;gap:8px;align-items:center"><button class="btn sm" type="button" data-modal-target="deposit-form">+ Input Setoran</button><a class="btn ghost sm" href="../index.php">← Kembali</a></div>
</div>
<dialog class="app-form-modal" id="deposit-form"><div class="modal-shell"><div class="modal-form-heading"><div><span class="eyebrow">Input transaksi</span><h2>Form Setoran Sampah</h2></div><button class="modal-close" type="button" data-modal-close aria-label="Tutup dialog">&times;</button></div><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><div class="form-grid"><div class="field"><label>Nasabah</label><select name="customer_id" required><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=e($c['customer_no'].' — '.$c['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Tanggal</label><input type="date" name="deposit_date" value="<?=date('Y-m-d')?>"></div></div>
<div class="section"><div class="section-head"><h2>Detail sampah</h2></div><div id="rows"><?php for($i=0;$i<4;$i++):?><div class="form-grid row" style="margin-bottom:8px"><div class="field"><select name="waste_type_id[]"><option value="">-- Pilih jenis --</option><?php foreach($wastes as $w):?><option value="<?=$w['id']?>"><?=e($w['name'])?> — <?=rupiah((float)$w['buy_price'])?>/kg</option><?php endforeach;?></select></div><div class="field"><input type="number" step="0.001" min="0" name="weight[]" placeholder="Berat (kg)"></div></div><?php endfor;?></div></div>
<div class="form-grid transaction-documentation"><div class="field"><label>Catatan</label><textarea name="notes"></textarea></div><div class="field"><label>Dokumentasi Transaksi</label><input type="file" name="documentation" accept="image/jpeg,image/png,image/webp,application/pdf"><small class="field-help">Foto bukti timbang atau dokumen pendukung. Maksimal 5 MB.</small></div></div><div class="actions"><button class="btn">Simpan Setoran</button><button class="btn ghost" type="button" data-modal-close>Batal</button></div></form></div></dialog>
<div class="section table-wrap"><div class="section-head"><h2>Data setoran terbaru</h2><a class="btn ghost sm" href="deposit_history.php">Lihat Semua</a></div><table class="table"><tr><th>Tanggal</th><th>No. Setoran</th><th>Nasabah</th><th class="right">Berat</th><th class="right">Nilai</th><th>Status</th></tr><?php foreach($recentDeposits as $row):?><tr><td><?=e($row['deposit_date'])?></td><td><b><?=e($row['receipt_no'])?></b></td><td><?=e($row['customer'])?></td><td class="right"><?=number_format((float)$row['total_weight'],2,',','.')?> kg</td><td class="right income"><?=rupiah((float)$row['total_amount'])?></td><td><span class="badge success"><?=e($row['status'])?></span></td></tr><?php endforeach;?><?php if(!$recentDeposits):?><tr><td colspan="6" class="empty">Belum ada data setoran.</td></tr><?php endif;?></table></div>
<?php require __DIR__.'/../includes/footer.php'; ?>