<?php
require_once __DIR__.'/../config/config.php';
$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-d');
$s=db()->prepare("SELECT type,COALESCE(SUM(amount),0) total FROM transactions WHERE company_id=? AND transaction_date BETWEEN ? AND ? GROUP BY type");$s->execute([current_company_id(),$from,$to]);$sum=['income'=>0,'expense'=>0];foreach($s as $r)$sum[$r['type']]=(float)$r['total'];
$s=db()->prepare("SELECT t.*,w.name wallet,c.name category FROM transactions t LEFT JOIN wallets w ON w.id=t.wallet_id LEFT JOIN categories c ON c.id=t.category_id WHERE t.company_id=? AND t.transaction_date BETWEEN ? AND ? ORDER BY t.transaction_date DESC");$s->execute([current_company_id(),$from,$to]);$rows=$s->fetchAll();$active='reports';$title='Laporan Keuangan';require __DIR__.'/../includes/header.php';?>
<div class="section-head"><div><h1>Laporan Keuangan</h1></div><div><a class="btn ghost sm" href="../index.php">← Kembali</a></div></div><div class="card"><form class="toolbar"><label>Dari <input type="date" name="from" value="<?=e($from)?>"></label><label>Sampai <input type="date" name="to" value="<?=e($to)?>"></label><button class="btn">Tampilkan</button></form></div>
<div class="grid section"><div class="card stat"><div class="label">PEMASUKAN</div><div class="value income"><?=rupiah($sum['income'])?></div></div><div class="card stat"><div class="label">PENGELUARAN</div><div class="value expense"><?=rupiah($sum['expense'])?></div></div><div class="card stat"><div class="label">SELISIH</div><div class="value"><?=rupiah($sum['income']-$sum['expense'])?></div></div></div>
<div class="section table-wrap"><table class="table"><tr><th>Tanggal</th><th>Keterangan</th><th>Dompet</th><th>Kategori</th><th>Jenis</th><th class="right">Nominal</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['transaction_date'])?></td><td><?=e($r['description'])?></td><td><?=e($r['wallet'])?></td><td><?=e($r['category'])?></td><td class="<?=e($r['type'])?>"><?=e($r['type'])?></td><td class="right"><?=rupiah((float)$r['amount'])?></td></tr><?php endforeach;?></table></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
