<?php
require_once __DIR__.'/../config/config.php';
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$a=(int)$_POST['from_wallet'];$b=(int)$_POST['to_wallet'];$amount=(float)$_POST['amount'];if($a!==$b&&$amount>0){$pdo=db();$pdo->beginTransaction();$pdo->prepare("UPDATE wallets SET balance=balance-? WHERE id=? AND company_id=?")->execute([$amount,$a,current_company_id()]);$pdo->prepare("UPDATE wallets SET balance=balance+? WHERE id=? AND company_id=?")->execute([$amount,$b,current_company_id()]);$pdo->prepare("INSERT INTO transfers(company_id,from_wallet,to_wallet,amount,transfer_date,description) VALUES(?,?,?,?,?,?)")->execute([current_company_id(),$a,$b,$amount,date('Y-m-d'),trim($_POST['description'])]);$pdo->commit();flash('success','Transfer berhasil.');}else flash('error','Dompet asal/tujuan harus berbeda dan nominal > 0.');redirect('transfer.php');}
$q=db()->prepare("SELECT * FROM wallets WHERE company_id=? ORDER BY name");$q->execute([current_company_id()]);$wallets=$q->fetchAll();$active='transfer';$title='Transfer Dompet';require __DIR__.'/../includes/header.php';?>
<div class="section-head">
  <div><h1>Transfer Antar Dompet</h1><p class="muted">Pindahkan saldo antar dompet/kas/rekening tanpa mempengaruhi total aset.</p></div>
  <a class="btn ghost sm" href="../index.php">← Kembali</a>
</div>
<div class="card form"><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><div class="form-grid"><div class="field"><label>Dari</label><select name="from_wallet"><?php foreach($wallets as $x):?><option value="<?=$x['id']?>"><?=e($x['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Ke</label><select name="to_wallet"><?php foreach($wallets as $x):?><option value="<?=$x['id']?>"><?=e($x['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Nominal</label><input type="number" name="amount" min="1" required></div><div class="field"><label>Keterangan</label><input name="description"></div></div><div class="actions"><button class="btn">Transfer</button><a class="btn ghost" href="wallet_detail.php">Lihat Detail Dompet</a></div></form></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
