<?php
require_once __DIR__.'/../config/config.php';$cid=current_company_id();$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$cid=current_company_id();$pdo->beginTransaction();try{$customerId=(int)$_POST['customer_id'];$walletId=(int)$_POST['wallet_id'];$amt=(float)$_POST['amount'];$s=$pdo->prepare("SELECT balance FROM customers WHERE id=? AND company_id=? FOR UPDATE");$s->execute([$customerId,$cid]);$bal=$s->fetchColumn();if($bal===false)throw new Exception('Nasabah tidak ditemukan.');$bal=(float)$bal;$w=$pdo->prepare("SELECT balance FROM wallets WHERE id=? AND company_id=? FOR UPDATE");$w->execute([$walletId,$cid]);$walletBalance=$w->fetchColumn();if($walletBalance===false)throw new Exception('Kas/rekening tidak ditemukan.');$walletBalance=(float)$walletBalance;if($amt<=0||$amt>$bal)throw new Exception('Saldo nasabah tidak mencukupi.');if($amt>$walletBalance)throw new Exception('Saldo kas/rekening tidak mencukupi.');$pdo->prepare("UPDATE customers SET balance=balance-? WHERE id=? AND company_id=?")->execute([$amt,$customerId,$cid]);$pdo->prepare("INSERT INTO withdrawals(company_id,customer_id,wallet_id,amount,withdrawal_date,description) VALUES(?,?,?,?,?,?)")->execute([$cid,$customerId,$walletId,$amt,$_POST['withdrawal_date'],trim($_POST['description'])]);$pdo->prepare("UPDATE wallets SET balance=balance-? WHERE id=? AND company_id=?")->execute([$amt,$walletId,$cid]);$pdo->commit();flash('success','Penarikan saldo berhasil.');redirect('withdrawal.php');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());redirect('withdrawal.php');}}
$c=$pdo->prepare("SELECT id,customer_no,name,balance FROM customers WHERE company_id=? AND status='active' ORDER BY name");$c->execute([$cid]);$customers=$c->fetchAll();$w=$pdo->prepare("SELECT id,name,balance FROM wallets WHERE company_id=?");$w->execute([$cid]);$wallets=$w->fetchAll();$recent=$pdo->prepare("SELECT x.withdrawal_date,c.name customer,w.name wallet,x.amount,x.description FROM withdrawals x LEFT JOIN customers c ON c.id=x.customer_id LEFT JOIN wallets w ON w.id=x.wallet_id WHERE x.company_id=? ORDER BY x.id DESC LIMIT 10");$recent->execute([$cid]);$recentWithdrawals=$recent->fetchAll();$active='withdrawal';$title='Penarikan Saldo';require __DIR__.'/../includes/header.php';?>
<div class="section-head">
  <div><h1>Penarikan Saldo Nasabah</h1><p class="muted">Proses penarikan saldo nasabah, otomatis kurangi saldo dan kas.</p></div>
  <div style="display:flex;gap:8px;align-items:center"><button class="btn danger sm" type="button" data-modal-target="withdrawal-form">+ Proses Penarikan</button><a class="btn ghost sm" href="../index.php">← Kembali</a></div>
</div>
<dialog class="app-form-modal" id="withdrawal-form"><div class="modal-shell"><div class="modal-form-heading"><div><span class="eyebrow">Input transaksi</span><h2>Form Penarikan Saldo</h2></div><button class="modal-close" type="button" data-modal-close aria-label="Tutup dialog">&times;</button></div><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><div class="form-grid"><div class="field"><label>Nasabah</label><select name="customer_id"><?php foreach($customers as $x):?><option value="<?=$x['id']?>"><?=e($x['customer_no'].' — '.$x['name'])?> (<?=rupiah((float)$x['balance'])?>)</option><?php endforeach;?></select></div><div class="field"><label>Kas/Rekening</label><select name="wallet_id"><?php foreach($wallets as $x):?><option value="<?=$x['id']?>"><?=e($x['name'])?> — <?=rupiah((float)$x['balance'])?></option><?php endforeach;?></select></div><div class="field"><label>Nominal</label><input type="number" min="1" step=".01" name="amount" required></div><div class="field"><label>Tanggal</label><input type="date" name="withdrawal_date" value="<?=date('Y-m-d') ?>"></div><div class="field full"><label>Keterangan</label><input name="description"></div></div><div class="actions"><button class="btn danger">Proses Penarikan</button><button class="btn ghost" type="button" data-modal-close>Batal</button></div></form></div></dialog>
<div class="section table-wrap"><div class="section-head"><h2>Data penarikan terbaru</h2><a class="btn ghost sm" href="withdrawal_history.php">Lihat Semua</a></div><table class="table"><tr><th>Tanggal</th><th>Nasabah</th><th>Kas/Rekening</th><th class="right">Nominal</th><th>Keterangan</th></tr><?php foreach($recentWithdrawals as $row):?><tr><td><?=e($row['withdrawal_date'])?></td><td><?=e($row['customer'])?></td><td><?=e($row['wallet'])?></td><td class="right expense"><?=rupiah((float)$row['amount'])?></td><td class="muted"><?=e($row['description'])?></td></tr><?php endforeach;?><?php if(!$recentWithdrawals):?><tr><td colspan="5" class="empty">Belum ada data penarikan.</td></tr><?php endif;?></table></div>
<?php require __DIR__.'/../includes/footer.php'; ?>